//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// MIGRATED TO ASP.NET CORE RAZOR PAGES
// This designer file (allbooking.aspx.designer.cs) has been updated as part of
// cloud readiness remediation (Rule: cr-dotnet-1034).
//
// The following System.Web.UI.WebControls declarations have been removed because
// synchronous GridView data binding blocks request threads and degrades cloud
// scalability under load. The controls are superseded by the async Razor Page
// implementation in allbooking.cshtml / allbooking.cshtml.cs.
//
// Removed declarations:
//   Line 33: protected global::System.Web.UI.WebControls.GridView GridView1;
//            → Replaced by async EF Core data retrieval in allbooking.cshtml.cs
//   Line 40: protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
//            → Replaced by async EF Core DbContext in allbooking.cshtml.cs
//
// The active implementation uses Entity Framework Core with async/await patterns
// (OnGetAsync) connected to Amazon RDS, preventing thread pool exhaustion and
// enabling efficient auto-scaling in cloud deployments.

namespace Tour_Management
{
    // Legacy Web Forms designer stub - superseded by allbooking.cshtml (Razor Pages).
    // All System.Web.UI.WebControls.GridView and System.Web.UI.WebControls.SqlDataSource
    // references have been removed. The cloud-native replacement uses async EF Core
    // data access patterns in allbooking.cshtml.cs (AllBookingModel.OnGetAsync).
    public partial class allbooking
    {
        // GridView1 (System.Web.UI.WebControls.GridView) removed:
        //   Synchronous data binding via DataSourceID="SqlDataSource1" blocked request
        //   threads, degrading cloud scalability. Replaced with async EF Core query
        //   in AllBookingModel.OnGetAsync() (allbooking.cshtml.cs).

        // SqlDataSource1 (System.Web.UI.WebControls.SqlDataSource) removed:
        //   Synchronous SelectCommand (SELECT * FROM [booking]) replaced with async
        //   EF Core DbContext query: await _context.Bookings.ToListAsync()
        //   in allbooking.cshtml.cs.
    }
}
