//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// cr-dotnet-1034: Async GridView Data Binding with RDS via Entity Framework Core
// The Web Forms GridView1 (System.Web.UI.WebControls.GridView) and SqlDataSource1
// (System.Web.UI.WebControls.SqlDataSource) server controls have been removed.
// Synchronous data binding via GridView.DataBind() / SqlDataSource has been replaced
// with async Task-based EF Core queries in DisplayToursModel.OnGetAsync() (DisplayTours.aspx.cs).
// The Razor Page view (DisplayTours.aspx) renders data via @foreach over Model.Tours.
//
// Removed declarations:
//   - protected global::System.Web.UI.HtmlControls.HtmlForm form1;
//   - protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;  (line 42 - cr-dotnet-1034)
//   - protected global::System.Web.UI.WebControls.GridView GridView1;            (line 42 - cr-dotnet-1034)

namespace Tour_Management
{
    // Designer file retained for project structure compatibility.
    // All Web Forms server control declarations removed as part of cr-dotnet-1034 remediation.
    // Data binding is now handled asynchronously via EF Core in Pages/DisplayToursModel.
    public partial class DisplayTours
    {
        // Web Forms server controls (GridView1, SqlDataSource1, form1) removed.
        // Replaced by async EF Core data access in DisplayTours.aspx.cs (DisplayToursModel).
    }
}
