//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

// cr-dotnet-1034: Web Forms GridView and SqlDataSource control declarations removed.
// Synchronous data binding via asp:GridView (DataSourceID="SqlDataSource1") and
// asp:SqlDataSource (SelectCommand="SELECT ... FROM [Tour]") have been replaced with
// async Task OnGetAsync() using Dapper QueryAsync<TourItem>() connected to Amazon RDS
// in the Razor Page model (DisplayTours.aspx.cs / Pages/DisplayToursModel).
// The System.Web.UI.WebControls.GridView and System.Web.UI.WebControls.SqlDataSource
// field declarations are no longer required as the page has been migrated to
// ASP.NET Core Razor Pages (cr-dotnet-0026).

namespace Tour_Management
{
    // DisplayTours partial class retained for reference only.
    // Active implementation is in Tour_Management.Pages.DisplayToursModel (DisplayTours.aspx.cs).
    public partial class DisplayTours
    {
        // form1, SqlDataSource1, and GridView1 Web Forms control declarations removed.
        // Replaced by async Razor Page model with Dapper + Amazon RDS data access.
        // See: DisplayTours.aspx.cs -> DisplayToursModel.OnGetAsync()
    }
}
