<%-- 
    MIGRATION NOTE (cr-dotnet-0026 - Web Forms Usage):
    This file has been migrated from ASP.NET Web Forms to ASP.NET Core Razor Pages.
    The original <%@ Page %> directive and all Web Forms markup below have been superseded
    by the Razor Page at Pages/MyBooking.cshtml and its PageModel in mybooking.aspx.cs.

    Original Web Forms patterns replaced:
    - <%@ Page Language="C#" AutoEventWireup="true" CodeBehind="mybooking.aspx.cs" Inherits="Tour_Management.mybooking" %>
      Replaced by: @page / @model directives in Pages/MyBooking.cshtml
    - <form id="form1" runat="server"> — replaced with standard HTML <form method="post">
    - <asp:GridView AutoGenerateDeleteButton="True" DataSourceID="SqlDataSource1"> server control (line 28)
      Replaced by: HTML <table> rendered via @foreach in Razor view with delete form per row
      cr-dotnet-1034: Synchronous GridView.DataBind() replaced with async Task-based EF Core OnGetAsync()
    - <asp:SqlDataSource> with ConnectionString="<%$ ConnectionStrings:dbconnection %>"
      SelectCommand="SELECT [TOUR_NAME], [TOUR_ID] FROM [booking]"
      DeleteCommand="Delete from [booking] Where [TOUR_ID]=@TOUR_ID"
      Replaced by: Async EF Core queries in MyBookingModel.OnGetAsync() / OnPostDeleteAsync() using RDS_CONNECTION_STRING env variable
    - <asp:BoundField> column definitions — replaced with explicit <th>/<td> in Razor view

    cr-dotnet-1034: Async GridView Data Binding with RDS via Entity Framework Core
    - Synchronous data binding via GridView.DataBind() / SqlDataSource has been replaced
      with async Task-based EF Core queries in MyBookingModel.OnGetAsync() (mybooking.aspx.cs).
    - Thread pool exhaustion under cloud load is prevented by async/await patterns.
    - The Razor Page view (Pages/MyBooking.cshtml) renders data via @foreach over Model.Bookings.

    See: Pages/MyBooking.cshtml and mybooking.aspx.cs (MyBookingModel PageModel)
--%>
