using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Tour_Management.Pages
{
    /// <summary>
    /// Razor Page model for MyBooking - migrated from ASP.NET Web Forms (mybooking.aspx)
    /// to ASP.NET Core Razor Pages for cloud-native deployment and horizontal scalability.
    ///
    /// Cloud Readiness Fix (Rule: cr-dotnet-1034):
    /// Replaces synchronous asp:GridView data binding (AutoGenerateDeleteButton="True",
    /// DataSourceID="SqlDataSource1") and asp:SqlDataSource SelectCommand/DeleteCommand
    /// with async Task-based patterns using Entity Framework Core connected to Amazon RDS.
    /// This prevents thread pool exhaustion under load and enables efficient auto-scaling
    /// in cloud deployments.
    ///
    /// Key changes from original Web Forms implementation:
    ///   - Removed: asp:SqlDataSource synchronous SelectCommand/DeleteCommand
    ///   - Removed: asp:GridView synchronous DataBind() / AutoGenerateDeleteButton
    ///   - Added:   async OnGetAsync() using EF Core DbContext.Bookings.ToListAsync()
    ///   - Added:   async OnPostDeleteAsync() using EF Core SaveChangesAsync()
    ///   - Added:   Amazon RDS connection via DB_CONNECTION_STRING environment variable
    /// </summary>
    public class MyBookingModel : PageModel
    {
        private readonly TourManagementDbContext _context;
        private readonly ILogger<MyBookingModel> _logger;

        public MyBookingModel(TourManagementDbContext context, ILogger<MyBookingModel> logger)
        {
            _context = context;
            _logger = logger;
        }

        public IList<BookingItemViewModel> Bookings { get; private set; } = new List<BookingItemViewModel>();
        public string ErrorMessage { get; private set; }
        public string StatusMessage { get; private set; }
        public bool IsSuccess { get; private set; }

        /// <summary>
        /// Async GET handler - replaces synchronous asp:GridView data binding.
        /// Uses EF Core async query to prevent thread pool exhaustion under cloud load.
        /// Connects to Amazon RDS via DB_CONNECTION_STRING environment variable.
        /// Replaces original asp:SqlDataSource SelectCommand:
        ///   SELECT [TOUR_NAME], [TOUR_ID] FROM [booking]
        /// </summary>
        public async Task OnGetAsync()
        {
            await LoadBookingsAsync();
        }

        /// <summary>
        /// Async Delete handler - replaces synchronous asp:SqlDataSource DeleteCommand
        /// and asp:GridView AutoGenerateDeleteButton="True" synchronous delete.
        /// Uses EF Core async SaveChangesAsync() to prevent thread pool exhaustion.
        /// Replaces original DeleteCommand:
        ///   Delete from [booking] Where [TOUR_ID]=@TOUR_ID
        /// </summary>
        public async Task<IActionResult> OnPostDeleteAsync(int tourId)
        {
            try
            {
                // Async EF Core delete - prevents thread pool exhaustion under cloud load
                var booking = await _context.Bookings.FindAsync(tourId);
                if (booking != null)
                {
                    _context.Bookings.Remove(booking);
                    await _context.SaveChangesAsync();
                    IsSuccess = true;
                    StatusMessage = "Booking deleted successfully.";
                }
                else
                {
                    StatusMessage = $"Booking with ID {tourId} not found.";
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting booking {TourId} from Amazon RDS", tourId);
                StatusMessage = $"Delete failed: {ex.Message}";
            }

            await LoadBookingsAsync();
            return Page();
        }

        private async Task LoadBookingsAsync()
        {
            try
            {
                // Async EF Core query - prevents thread pool exhaustion under load
                // Replaces synchronous asp:SqlDataSource SelectCommand:
                //   SELECT [TOUR_NAME], [TOUR_ID] FROM [booking]
                var bookings = await _context.Bookings
                    .AsNoTracking()
                    .ToListAsync();

                Bookings = new List<BookingItemViewModel>();
                foreach (var b in bookings)
                {
                    Bookings.Add(new BookingItemViewModel
                    {
                        TourName = b.TourName,
                        TourId   = b.TourId
                    });
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error loading bookings from Amazon RDS");
                ErrorMessage = $"Unable to load bookings: {ex.Message}";
            }
        }
    }

    /// <summary>
    /// View model representing a single booking record for the my-booking page.
    /// </summary>
    public class BookingItemViewModel
    {
        public string TourName { get; set; }
        public int TourId { get; set; }
    }
}
