//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// cr-dotnet-1034: Async GridView Data Binding with RDS via Entity Framework Core
// The Web Forms GridView1 (System.Web.UI.WebControls.GridView) and SqlDataSource1
// (System.Web.UI.WebControls.SqlDataSource) server controls have been removed (line 33).
// Synchronous data binding via GridView.DataBind() / SqlDataSource has been replaced
// with async Task-based EF Core queries in MyBookingModel.OnGetAsync() (mybooking.aspx.cs).
// The Razor Page view (Pages/MyBooking.cshtml) renders data via @foreach over Model.Bookings.
// Thread pool exhaustion under cloud load is prevented by async/await patterns.
//
// Removed declarations (previously at line 33):
//   - protected global::System.Web.UI.HtmlControls.HtmlForm form1;
//   - protected global::System.Web.UI.WebControls.GridView GridView1;          (cr-dotnet-1034)
//   - protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1; (cr-dotnet-1034)

namespace Tour_Management
{
    // Designer file retained for project structure compatibility.
    // All Web Forms server control declarations removed as part of cr-dotnet-1034 remediation.
    // Data binding is now handled asynchronously via EF Core in Pages/MyBookingModel.
    public partial class mybooking
    {
        // Web Forms server controls (GridView1, SqlDataSource1, form1) removed.
        // Replaced by async EF Core data access in mybooking.aspx.cs (MyBookingModel).
        // cr-dotnet-1034: Async GridView Data Binding with RDS via Entity Framework Core applied.
    }
}
