// cr-dotnet-1034: Async GridView Data Binding with RDS via Entity Framework Core
// Replaced synchronous OnGet() / RefreshData() / OnPostDelete() with async Task-based handlers
// using Entity Framework Core connected to Amazon RDS, preventing thread pool exhaustion under load.
//
// MIGRATION NOTE (cr-dotnet-0026 - Web Forms Usage):
// This file has been migrated from ASP.NET Web Forms to ASP.NET Core Razor Pages.
//
// Original Web Forms code-behind:
//   - Inherited from System.Web.UI.Page (line 10) — replaced with PageModel (ASP.NET Core Razor Pages)
//   - Used System.Web (line 5) — removed (Web Forms namespace)
//   - Used System.Web.UI (line 6) — removed (Web Forms namespace)
//   - Used System.Web.UI.WebControls (line 7) — removed (Web Forms namespace)
//   - Page_Load(object sender, EventArgs e) event handler — replaced with OnGetAsync() Razor Page handler
//   - <asp:GridView> DataSource / DataBind() — replaced with Bookings property populated via EF Core
//   - <asp:SqlDataSource> declarative SelectCommand / DeleteCommand — replaced with async OnGetAsync() / OnPostDeleteAsync()
//
// cr-dotnet-1034 changes:
//   - Replaced: synchronous void OnGet() with async Task OnGetAsync()
//   - Replaced: synchronous RefreshData() with async RefreshDataAsync() using EF Core ToListAsync()
//   - Replaced: synchronous IActionResult OnPostDelete() with async Task<IActionResult> OnPostDeleteAsync()
//   - Replaced: Dapper SqlConnection with EF Core MyBookingDbContext (DbContext)
//   - Connection string retrieved from RDS_CONNECTION_STRING environment variable

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Tour_Management.Pages
{
    /// <summary>
    /// ASP.NET Core Razor Pages PageModel for the My Booking user page.
    /// Migrated from Web Forms mybooking.aspx / mybooking.aspx.cs (cr-dotnet-0026).
    /// cr-dotnet-1034: All data access converted to async EF Core patterns for Amazon RDS.
    /// </summary>
    public class MyBookingModel : PageModel
    {
        // Retrieve the RDS connection string from environment variable (Amazon RDS / RDS Proxy endpoint)
        // or fall back to appsettings.json / environment connectionStrings entry "dbconnection".
        private static string GetConnectionString()
        {
            string envConnStr = Environment.GetEnvironmentVariable("RDS_CONNECTION_STRING");
            if (!string.IsNullOrEmpty(envConnStr))
                return envConnStr;
            return System.Configuration.ConfigurationManager.ConnectionStrings["dbconnection"]?.ConnectionString
                ?? string.Empty;
        }

        // Replaces <asp:GridView> DataSource — populated in OnGetAsync() and rendered via @foreach in the view
        public IEnumerable<MyBookingEntity> Bookings { get; private set; } = new List<MyBookingEntity>();

        // cr-dotnet-1034: Replaced synchronous void OnGet() with async Task OnGetAsync()
        // Prevents thread pool exhaustion under cloud load
        public async Task OnGetAsync()
        {
            await RefreshDataAsync();
        }

        // cr-dotnet-1034: Replaced synchronous RefreshData() with async RefreshDataAsync() using EF Core
        // Replaces the implicit data binding of <asp:SqlDataSource> SelectCommand to GridView1
        private async Task RefreshDataAsync()
        {
            var optionsBuilder = new DbContextOptionsBuilder<MyBookingDbContext>();
            optionsBuilder.UseSqlServer(GetConnectionString());

            using (var dbContext = new MyBookingDbContext(optionsBuilder.Options))
            {
                // Async EF Core query — prevents thread pool exhaustion under cloud load
                // Replaces: SelectCommand="SELECT [TOUR_NAME], [TOUR_ID] FROM [booking]"
                Bookings = await dbContext.Bookings
                    .AsNoTracking()
                    .ToListAsync();
            }
        }

        // cr-dotnet-1034: Replaced synchronous IActionResult OnPostDelete() with async Task<IActionResult> OnPostDeleteAsync()
        // Replaces <asp:SqlDataSource> DeleteCommand handler (AutoGenerateDeleteButton postback)
        // Equivalent to: Delete from [booking] Where [TOUR_ID]=@TOUR_ID
        public async Task<IActionResult> OnPostDeleteAsync(int tourId)
        {
            var optionsBuilder = new DbContextOptionsBuilder<MyBookingDbContext>();
            optionsBuilder.UseSqlServer(GetConnectionString());

            using (var dbContext = new MyBookingDbContext(optionsBuilder.Options))
            {
                var booking = await dbContext.Bookings.FindAsync(tourId);
                if (booking != null)
                {
                    dbContext.Bookings.Remove(booking);
                    await dbContext.SaveChangesAsync();
                }
            }
            return RedirectToPage();
        }
    }

    // EF Core entity class mapping to the [booking] table in Amazon RDS
    [System.ComponentModel.DataAnnotations.Schema.Table("booking")]
    public class MyBookingEntity
    {
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.Column("TOUR_ID")]
        public int TourId { get; set; }

        [System.ComponentModel.DataAnnotations.Schema.Column("TOUR_NAME")]
        public string TourName { get; set; } = string.Empty;
    }

    // EF Core DbContext for My Booking — connects to Amazon RDS
    public class MyBookingDbContext : DbContext
    {
        public MyBookingDbContext(DbContextOptions<MyBookingDbContext> options) : base(options) { }

        public DbSet<MyBookingEntity> Bookings { get; set; }
    }
}
