<%--
    cr-dotnet-1034: Async GridView Data Binding with RDS via Entity Framework Core
    
    Line 28 (original): <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
                         AutoGenerateDeleteButton="True" DataSourceID="SqlDataSource1" ...>
    Fix applied: Replaced synchronous GridView server control with async Razor Page table rendering.
    
    The active implementation is at: Pages/MyBooking.cshtml and Pages/MyBooking.cshtml.cs
    using async Task OnGetAsync() with Entity Framework Core ToListAsync() connected to Amazon RDS.
    
    MIGRATION NOTE (cr-dotnet-0026 + cr-dotnet-1034): This Web Forms page (mybooking.aspx) has been
    migrated to ASP.NET Core Razor Pages with async data binding.
    - Removed: <asp:GridView AutoGenerateDeleteButton="True"> synchronous server control (line 28)
    - Removed: <asp:SqlDataSource runat="server"> synchronous data source
    - Replaced: synchronous GridView.DataBind() with async Task OnGetAsync() + EF Core ToListAsync()
    - Replaced: SqlDataSource DeleteCommand with async OnPostDeleteAsync() handler
    - Replaced: SqlDataSource ConnectionString binding with environment variable DB_CONNECTION_STRING
    - Prevents thread pool exhaustion under AWS cloud load; enables efficient auto-scaling
    
    This file is retained for reference only.
--%>
<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="mybooking.aspx.cs" Inherits="Tour_Management.mybooking" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; YOUR CURRENT BOOKING</h1>
    <form id="form1" runat="server">
        <%--
            cr-dotnet-1034 (Line 28): Replaced synchronous <asp:GridView AutoGenerateDeleteButton="True">
            server control with async Razor Page table rendering in Pages/MyBooking.cshtml.
            Data is now loaded via async Task OnGetAsync() using EF Core ToListAsync() on Amazon RDS.
            Delete action migrated to async OnPostDeleteAsync() handler.
            Original: <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
                       AutoGenerateDeleteButton="True" DataSourceID="SqlDataSource1" ...>
        --%>

        <%--
            cr-dotnet-1034: Replaced synchronous <asp:SqlDataSource> with async EF Core.
            Original: <asp:SqlDataSource ID="SqlDataSource1" runat="server"
                       ConnectionString="<%$ ConnectionStrings:dbconnection %>"
                       SelectCommand="SELECT [TOUR_NAME], [TOUR_ID] FROM [booking]"
                       DeleteCommand="Delete from [booking] Where [TOUR_ID]=@TOUR_ID">
            Replaced by: Entity Framework Core MyBookingDbContext with async ToListAsync()
                         and async ExecuteDeleteAsync() connected to Amazon RDS.
        --%>
    </form>
</body>
</html>
