//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// MIGRATED TO ASP.NET CORE RAZOR PAGES
// This designer file (TourCrud.aspx.designer.cs) has been updated as part of
// cloud readiness remediation (Rule: cr-dotnet-1034).
//
// The following System.Web.UI.WebControls declarations have been removed because
// synchronous GridView data binding blocks request threads and degrades cloud
// scalability under load. The controls are superseded by the async Razor Page
// implementation in TourCrud.cshtml / TourCrud.cshtml.cs.
//
// Removed declarations:
//   Line 33: protected global::System.Web.UI.WebControls.GridView GridView1;
//            → Replaced by async EF Core data retrieval in TourCrud.cshtml.cs
//   Line 40: protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
//            → Replaced by async EF Core DbContext in TourCrud.cshtml.cs
//
// The active implementation uses Entity Framework Core with async/await patterns
// (OnGetAsync, OnPostUpdateAsync, OnPostDeleteAsync) connected to Amazon RDS,
// preventing thread pool exhaustion and enabling efficient auto-scaling.

namespace Tour_Management
{
    // Legacy Web Forms designer stub - superseded by TourCrud.cshtml (Razor Pages).
    // All System.Web.UI.WebControls.GridView and System.Web.UI.WebControls.SqlDataSource
    // references have been removed. The cloud-native replacement uses async EF Core
    // data access patterns in TourCrud.cshtml.cs (TourCrudModel).
    public partial class TourCrud
    {
        // GridView1 (System.Web.UI.WebControls.GridView) removed:
        //   Synchronous data binding via DataSourceID="SqlDataSource1" blocked request
        //   threads, degrading cloud scalability. Replaced with async EF Core query
        //   in TourCrudModel.OnGetAsync() (TourCrud.cshtml.cs).

        // SqlDataSource1 (System.Web.UI.WebControls.SqlDataSource) removed:
        //   Synchronous SelectCommand/UpdateCommand/DeleteCommand execution replaced
        //   with async EF Core DbContext operations in TourCrud.cshtml.cs.
    }
}
