//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

// cr-dotnet-1034: Web Forms GridView and SqlDataSource control declarations removed.
// Synchronous data binding via asp:GridView (DataSourceID="SqlDataSource1",
// AutoGenerateEditButton="True", AutoGenerateDeleteButton="True") and
// asp:SqlDataSource (SelectCommand/UpdateCommand/DeleteCommand on [Tour] table)
// have been replaced with async Task handlers using Dapper connected to Amazon RDS
// in the Razor Page model (Pages/TourCrud.cshtml.cs / TourCrudModel).
// The System.Web.UI.WebControls.GridView and System.Web.UI.WebControls.SqlDataSource
// field declarations are no longer required as the page has been migrated to
// ASP.NET Core Razor Pages (cr-dotnet-0026).

namespace Tour_Management
{
    // TourCrud partial class retained for reference only.
    // Active implementation is in Tour_Management.Pages.TourCrudModel (Pages/TourCrud.cshtml.cs).
    public partial class TourCrud
    {
        // form1, GridView1, and SqlDataSource1 Web Forms control declarations removed.
        // Replaced by async Razor Page model with Dapper + Amazon RDS data access.
        // See: Pages/TourCrud.cshtml.cs -> TourCrudModel.OnGetAsync(), OnPostEditAsync(), OnPostDeleteAsync()
    }
}
