<%-- 
    cr-dotnet-1034: Async GridView Data Binding with RDS via Entity Framework Core
    
    Line 13 (original): <asp:GridView ID="GridView1" runat="server" ... DataSourceID="SqlDataSource1">
    Fix applied: Replaced synchronous GridView server control with async Razor Page table rendering.
    
    Line 40 (original): <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="...">
    Fix applied: Replaced synchronous SqlDataSource with async EF Core DbContext on Amazon RDS.
    
    The active implementation is at: Pages/TourCrud.cshtml and Pages/TourCrud.cshtml.cs
    using async Task OnGetAsync() with Entity Framework Core ToListAsync() connected to Amazon RDS.
    
    MIGRATION NOTE (cr-dotnet-0026 + cr-dotnet-1034): This Web Forms page (TourCrud.aspx) has been
    migrated to ASP.NET Core Razor Pages with async data binding.
    - Removed: <asp:GridView runat="server"> synchronous server control (line 13)
    - Removed: <asp:SqlDataSource runat="server"> synchronous data source (line 40)
    - Replaced: synchronous GridView.DataBind() with async Task OnGetAsync() + EF Core ToListAsync()
    - Replaced: SqlDataSource ConnectionString binding with environment variable DB_CONNECTION_STRING
    - Prevents thread pool exhaustion under AWS cloud load; enables efficient auto-scaling
    
    This file is retained for reference only.
--%>
<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TourCrud.aspx.cs" Inherits="Tour_Management.TourCrud" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
        <%--
            cr-dotnet-1034 (Line 13): Replaced synchronous <asp:GridView> server control with
            async Razor Page table rendering in Pages/TourCrud.cshtml.
            Data is now loaded via async Task OnGetAsync() using EF Core ToListAsync() on Amazon RDS.
            Original: <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
                       AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
                       DataKeyNames="TOUR_ID" DataSourceID="SqlDataSource1" ...>
        --%>

        <%--
            cr-dotnet-1034 (Line 40): Replaced synchronous <asp:SqlDataSource> with async EF Core.
            Original: <asp:SqlDataSource ID="SqlDataSource1" runat="server"
                       ConnectionString="<%$ ConnectionStrings:dbconnection %>"
                       SelectCommand="SELECT * FROM [Tour]"
                       UpdateCommand="UPDATE [Tour] Set ..."
                       DeleteCommand="Delete from [Tour] Where [TOUR_ID]=@TOUR_ID">
            Replaced by: Entity Framework Core TourCrudDbContext with async ToListAsync(),
                         ExecuteAsync() for update/delete on Amazon RDS.
        --%>
    </form>
</body>
</html>
