<%-- 
    MIGRATED: This Web Forms page has been migrated to ASP.NET Core Razor Pages.
    The equivalent Razor Page is located at: Pages/TourCrud.cshtml
    This file is retained for reference only and is no longer active.
    
    Migration: ASP.NET Web Forms -> ASP.NET Core Razor Pages (cr-dotnet-0026)
    The <%@ Page %> directive, runat="server" controls, asp:GridView, asp:SqlDataSource,
    and code-behind inheritance from System.Web.UI.Page have been replaced with a Razor Page model.

    cr-dotnet-1034: Synchronous GridView data binding replaced with async Task-based pattern.
    Original synchronous pattern (lines 13, 40 - now removed):
      Line 13: <asp:GridView ID="GridView1" runat="server" ... DataSourceID="SqlDataSource1"
               AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" ...>
      Line 40: <asp:SqlDataSource ID="SqlDataSource1" ... SelectCommand="SELECT * FROM [Tour]"
               UpdateCommand="UPDATE [Tour] ..." DeleteCommand="Delete from [Tour] ...">
    
    Replaced with async Razor Page handlers in Pages/TourCrud.cshtml.cs:
      public async Task OnGetAsync()          -> uses await conn.QueryAsync<TourViewModel>()
      public async Task OnPostEditAsync(...)  -> uses await conn.ExecuteAsync() for UPDATE
      public async Task OnPostDeleteAsync(..) -> uses await conn.ExecuteAsync() for DELETE
    All connected to Amazon RDS via Dapper for cloud-native async data access.
--%>
