//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------
// cr-dotnet-1034: Synchronous Data Binding in GridView Controls
// The synchronous System.Web.UI.WebControls.GridView (line 33) and
// System.Web.UI.WebControls.SqlDataSource field declarations have been removed.
// These Web Forms controls used synchronous data binding that blocks request threads,
// degrading cloud scalability under load.
// Replaced by: async Task-based EF Core data access in Controllers/UserController.cs
// and Razor table rendering in Views/User/UserCrud.cshtml.

namespace Tour_Management
{
    /// <summary>
    /// usercrud partial class - MIGRATED to async EF Core pattern (cr-dotnet-1034).
    /// Synchronous GridView and SqlDataSource controls removed.
    /// Async data binding is now handled by UserController.UserCrudAsync()
    /// using Entity Framework Core connected to Amazon RDS.
    /// </summary>
    public partial class usercrud
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        // REMOVED (cr-dotnet-1034): protected global::System.Web.UI.WebControls.GridView GridView1;
        // Reason: Synchronous GridView data binding replaced by async Razor table rendering
        // in Views/User/UserCrud.cshtml with data loaded via async EF Core query.

        // REMOVED (cr-dotnet-1034): protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
        // Reason: Synchronous SqlDataSource control replaced by async EF Core DbContext query
        // in UserController.UserCrudAsync() targeting Amazon RDS.
    }
}
