using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Tour_Management.Pages
{
    /// <summary>
    /// Razor Page model for My Bookings view with delete capability.
    /// cr-dotnet-1034: Replaced synchronous GridView/SqlDataSource data binding with
    /// async Task-based patterns using Entity Framework Core connected to Amazon RDS,
    /// preventing thread pool exhaustion under load and enabling efficient auto-scaling.
    ///
    /// Migrated from ASP.NET Web Forms (mybooking.aspx / mybooking.aspx.cs)
    /// to ASP.NET Core Razor Pages to enable cloud-native deployment on AWS.
    ///
    /// Replaces:
    ///   - using System.Web;                (line 5 in original mybooking.aspx.cs)
    ///   - using System.Web.UI;             (line 6 in original mybooking.aspx.cs)
    ///   - using System.Web.UI.WebControls; (line 7 in original mybooking.aspx.cs)
    ///   - public partial class mybooking : System.Web.UI.Page  (line 10 in original)
    ///   - asp:GridView AutoGenerateDeleteButton="True" (synchronous, line 12 original .aspx)
    ///   - asp:SqlDataSource SelectCommand/DeleteCommand (line 33 original .aspx)
    /// </summary>
    public class MyBookingModel : PageModel
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger<MyBookingModel> _logger;

        public MyBookingModel(IConfiguration configuration, ILogger<MyBookingModel> logger)
        {
            _configuration = configuration;
            _logger = logger;
        }

        public IEnumerable<MyBookingViewModel> Bookings { get; set; } = new List<MyBookingViewModel>();
        public string StatusMessage { get; set; } = string.Empty;
        public bool IsSuccess { get; set; }

        /// <summary>
        /// Retrieves the database connection string from environment variable (AWS RDS endpoint)
        /// with fallback to appsettings.json / Web.config for local development.
        /// </summary>
        private string GetConnectionString()
        {
            string envConnStr = Environment.GetEnvironmentVariable("DB_CONNECTION_STRING");
            if (!string.IsNullOrEmpty(envConnStr))
                return envConnStr;
            return _configuration.GetConnectionString("dbconnection");
        }

        /// <summary>
        /// Creates an EF Core DbContext configured for Amazon RDS via environment variable
        /// or appsettings connection string.
        /// </summary>
        private MyBookingDbContext CreateDbContext()
        {
            var optionsBuilder = new DbContextOptionsBuilder<MyBookingDbContext>();
            optionsBuilder.UseSqlServer(GetConnectionString());
            return new MyBookingDbContext(optionsBuilder.Options);
        }

        /// <summary>
        /// cr-dotnet-1034: Async OnGetAsync replaces synchronous Page_Load / GridView.DataBind().
        /// Uses Entity Framework Core async query (ToListAsync) connected to Amazon RDS,
        /// preventing thread pool exhaustion and enabling efficient auto-scaling.
        /// Replaces: asp:GridView DataSourceID="SqlDataSource1" (synchronous binding, line 12 original)
        ///           asp:SqlDataSource SelectCommand="SELECT [TOUR_NAME], [TOUR_ID] FROM [booking]"
        /// </summary>
        public async Task OnGetAsync()
        {
            await LoadBookingsAsync();
        }

        /// <summary>
        /// cr-dotnet-1034: Async data load using EF Core ToListAsync() — replaces synchronous
        /// GridView data binding via SqlDataSource. Prevents thread pool exhaustion under load.
        /// Replaces: asp:SqlDataSource SelectCommand="SELECT [TOUR_NAME], [TOUR_ID] FROM [booking]"
        /// </summary>
        private async Task LoadBookingsAsync()
        {
            try
            {
                using (var dbContext = CreateDbContext())
                {
                    // Async EF Core query — replaces synchronous GridView/SqlDataSource binding
                    Bookings = await dbContext.Bookings
                        .AsNoTracking()
                        .ToListAsync();
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error loading bookings from database.");
                StatusMessage = "Error loading bookings. Please try again.";
                IsSuccess = false;
            }
        }

        /// <summary>
        /// cr-dotnet-1034: Async OnPostDeleteAsync replaces synchronous GridView AutoGenerateDeleteButton.
        /// Uses EF Core async SaveChangesAsync() connected to Amazon RDS.
        /// Replaces: asp:SqlDataSource DeleteCommand="Delete from [booking] Where [TOUR_ID]=@TOUR_ID"
        /// </summary>
        public async Task<IActionResult> OnPostDeleteAsync(int deleteTourId)
        {
            try
            {
                using (var dbContext = CreateDbContext())
                {
                    var booking = await dbContext.Bookings.FindAsync(deleteTourId);
                    if (booking != null)
                    {
                        dbContext.Bookings.Remove(booking);
                        // Async SaveChangesAsync — replaces synchronous SqlDataSource DeleteCommand
                        await dbContext.SaveChangesAsync();
                    }
                }

                _logger.LogInformation("Booking deleted successfully: TourId={TourId}", deleteTourId);
                StatusMessage = "Booking deleted successfully.";
                IsSuccess = true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting booking: TourId={TourId}", deleteTourId);
                StatusMessage = "Error deleting booking. Please try again.";
                IsSuccess = false;
            }

            await LoadBookingsAsync();
            return Page();
        }
    }

    /// <summary>
    /// Entity model representing a user's Booking record.
    /// cr-dotnet-1034: Replaces auto-generated columns from asp:GridView DataKeyNames="TOUR_ID"
    /// in the original Web Forms page. Columns: TOUR_NAME, TOUR_ID.
    /// </summary>
    [Table("booking")]
    public class MyBookingViewModel
    {
        [Key]
        [Column("TOUR_ID")]
        public int TourId { get; set; }

        [Column("TOUR_NAME")]
        public string TourName { get; set; } = string.Empty;
    }

    /// <summary>
    /// EF Core DbContext for My Booking data — replaces SqlDataSource control.
    /// cr-dotnet-1034: Enables async data access patterns via Entity Framework Core
    /// connected to Amazon RDS, preventing thread pool exhaustion under cloud load.
    /// </summary>
    public class MyBookingDbContext : DbContext
    {
        public MyBookingDbContext(DbContextOptions<MyBookingDbContext> options) : base(options) { }

        public DbSet<MyBookingViewModel> Bookings { get; set; }
    }
}
