// cr-dotnet-1034: Async GridView Data Binding with RDS via Entity Framework Core
// MIGRATION NOTE (cr-dotnet-0026 + cr-dotnet-1034): ASP.NET Core Razor Pages PageModel for MyBooking page.
// Migrated from ASP.NET Web Forms (mybooking.aspx / mybooking.aspx.cs) to ASP.NET Core Razor Pages.
// - Removed: System.Web (line 4), System.Web.UI (line 5), System.Web.UI.WebControls (line 6) namespaces
// - Removed: System.Web.UI.Page base class (line 10) and related Web Forms references
// - Replaced: System.Web.UI.Page base class with PageModel
// - Replaced: synchronous Page_Load + GridView.DataBind() with async Task OnGetAsync()
// - cr-dotnet-1034: Replaced synchronous Dapper SqlConnection with async Entity Framework Core ToListAsync()
// - Replaced: <asp:GridView AutoGenerateDeleteButton="True"> + <asp:SqlDataSource> with async EF Core + Razor table
// - Replaced: SqlDataSource DeleteCommand with async OnPostDeleteAsync() handler
// - Replaced: SqlDataSource ConnectionString binding with environment variable DB_CONNECTION_STRING (Amazon RDS)
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Tour_Management.Pages
{
    /// <summary>
    /// Razor Pages PageModel for the My Bookings page.
    /// cr-dotnet-1034: Uses async Task OnGetAsync() with Entity Framework Core ToListAsync()
    /// connected to Amazon RDS, preventing thread pool exhaustion under cloud load.
    /// </summary>
    public class MyBookingModel : PageModel
    {
        /// <summary>
        /// Represents a single booking record for the current user.
        /// </summary>
        public class BookingRecord
        {
            public int TourId { get; set; }
            public string TourName { get; set; }
        }

        /// <summary>
        /// List of bookings loaded from Amazon RDS via async EF Core query.
        /// cr-dotnet-1034: Replaces synchronous <asp:GridView> + <asp:SqlDataSource> server controls.
        /// </summary>
        public List<BookingRecord> Bookings { get; private set; } = new List<BookingRecord>();

        // Retrieve connection string from environment variable (Amazon RDS Proxy endpoint)
        private static string GetConnectionString()
        {
            return Environment.GetEnvironmentVariable("DB_CONNECTION_STRING")
                ?? System.Configuration.ConfigurationManager.ConnectionStrings["dbconnection"]?.ConnectionString;
        }

        private DbContextOptions<MyBookingPageDbContext> BuildDbOptions()
        {
            var optionsBuilder = new DbContextOptionsBuilder<MyBookingPageDbContext>();
            optionsBuilder.UseSqlServer(GetConnectionString());
            return optionsBuilder.Options;
        }

        // cr-dotnet-1034: Replaced synchronous OnGet() + GridView.DataBind() with async Task OnGetAsync()
        // Uses Entity Framework Core ToListAsync() for non-blocking Amazon RDS data access
        public async Task OnGetAsync()
        {
            // cr-dotnet-1034: Replaces synchronous <asp:SqlDataSource SelectCommand="SELECT [TOUR_NAME], [TOUR_ID] FROM [booking]">
            // with async EF Core ToListAsync() - prevents thread pool exhaustion under AWS cloud load
            using (var dbContext = new MyBookingPageDbContext(BuildDbOptions()))
            {
                Bookings = await dbContext.BookingRecords.ToListAsync();
            }
        }

        // cr-dotnet-1034: Async OnPostDeleteAsync replaces synchronous AutoGenerateDeleteButton delete action
        // Replaces: DeleteCommand="Delete from [booking] Where [TOUR_ID]=@TOUR_ID"
        public async Task<IActionResult> OnPostDeleteAsync(int tourId)
        {
            using (var dbContext = new MyBookingPageDbContext(BuildDbOptions()))
            {
                var booking = await dbContext.BookingRecords.FindAsync(tourId);
                if (booking != null)
                {
                    dbContext.BookingRecords.Remove(booking);
                    await dbContext.SaveChangesAsync();
                }
            }
            return RedirectToPage();
        }
    }

    // cr-dotnet-1034: Entity Framework Core DbContext for async data access to Amazon RDS
    public class MyBookingPageDbContext : DbContext
    {
        public MyBookingPageDbContext(DbContextOptions<MyBookingPageDbContext> options) : base(options) { }

        public DbSet<MyBookingModel.BookingRecord> BookingRecords { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MyBookingModel.BookingRecord>(entity =>
            {
                entity.ToTable("booking");
                entity.HasKey(e => e.TourId);
                entity.Property(e => e.TourId).HasColumnName("TOUR_ID");
                entity.Property(e => e.TourName).HasColumnName("TOUR_NAME");
            });
        }
    }
}
