// Migrated from Web Forms (mybooking.aspx.cs) to ASP.NET Core Razor Pages (cr-dotnet-0026)
// Changes:
//   - Removed: using System.Web.UI;                    (line 5 - Web Forms namespace)
//   - Removed: using System.Web.UI.WebControls;        (line 6 - Web Forms namespace)
//   - Removed: inheritance from System.Web.UI.Page     (line 10 - Web Forms base class)
//   - Replaced: Page_Load event handler                (line 12 - Web Forms lifecycle)
//     with OnGetAsync() method in PageModel
//   - Replaced: asp:SqlDataSource declarative data binding
//     with explicit Dapper query in OnGetAsync()
//   - Replaced: asp:GridView with AutoGenerateDeleteButton
//     with strongly-typed Razor table and OnPostDeleteAsync() handler
//   - Replaced: DeleteCommand on asp:SqlDataSource
//     with explicit Dapper delete in OnPostDeleteAsync()

using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Tour_Management.Pages
{
    public class MyBookingModel : PageModel
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger<MyBookingModel> _logger;

        public MyBookingModel(IConfiguration configuration, ILogger<MyBookingModel> logger)
        {
            _configuration = configuration;
            _logger = logger;
        }

        public IEnumerable<MyBookingViewModel> Bookings { get; set; } = new List<MyBookingViewModel>();
        public string StatusMessage { get; set; } = string.Empty;

        // Retrieve the RDS Proxy connection string from environment variable,
        // falling back to the appsettings.json connectionString for local development.
        private string GetConnectionString()
        {
            return Environment.GetEnvironmentVariable("DB_CONNECTION_STRING")
                ?? _configuration.GetConnectionString("dbconnection")
                ?? string.Empty;
        }

        // Replaces Web Forms Page_Load event (line 12 in original code-behind)
        // and asp:SqlDataSource SelectCommand="SELECT [TOUR_NAME], [TOUR_ID] FROM [booking]"
        public async Task OnGetAsync()
        {
            // Use Dapper with RDS Proxy-backed SqlConnection for cloud-native connection pooling.
            using (IDbConnection conn = new SqlConnection(GetConnectionString()))
            {
                string selectQuery = "SELECT [TOUR_NAME], [TOUR_ID] FROM [booking]";
                Bookings = await conn.QueryAsync<MyBookingViewModel>(selectQuery);
            }
        }

        // Replaces AutoGenerateDeleteButton on asp:GridView with
        // DeleteCommand="Delete from [booking] Where [TOUR_ID]=@TOUR_ID" on asp:SqlDataSource
        public async Task<IActionResult> OnPostDeleteAsync(int tourId)
        {
            try
            {
                using (IDbConnection conn = new SqlConnection(GetConnectionString()))
                {
                    string deleteQuery = "DELETE FROM [booking] WHERE [TOUR_ID]=@TourId";
                    await conn.ExecuteAsync(deleteQuery, new { TourId = tourId });
                }
                _logger.LogInformation("Booking for tour {TourId} deleted successfully.", tourId);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting booking for tour {TourId}.", tourId);
                StatusMessage = "Delete failed. Please try again.";
            }

            return RedirectToPage();
        }
    }

    public class MyBookingViewModel
    {
        public int TourId { get; set; }
        public string TourName { get; set; } = string.Empty;
    }
}
