// Migrated from Web Forms (TourCrud.aspx.cs) to ASP.NET Core Razor Pages (cr-dotnet-0026)
// cr-dotnet-0010: Replaced Web.config / ConfigurationManager connection string lookup with
//                 Environment.GetEnvironmentVariable("DB_CONNECTION_STRING") so that
//                 configuration is injected at runtime (AWS ECS/EB environment variable or
//                 AWS Systems Manager Parameter Store) rather than baked into build artifacts
//                 via Web.Debug.config / Web.Release.config XDT transformations.
// Changes:
//   - Removed: using System.Web.UI;                    (line 5 - Web Forms namespace)
//   - Removed: using System.Web.UI.WebControls;        (line 6 - Web Forms namespace)
//   - Removed: inheritance from System.Web.UI.Page     (line 13 - Web Forms base class)
//   - Replaced: Page_Load / IsPostBack pattern         (line 15 - Web Forms lifecycle)
//     with OnGetAsync() method in PageModel
//   - Replaced: refreshdata() with GridView.DataBind() (line 18 - Web Forms data binding)
//     with a strongly-typed Tours list populated in OnGetAsync()
//   - Replaced: asp:SqlDataSource declarative data binding
//     with explicit Dapper queries in handler methods
//   - Added: OnPostEditAsync() and OnPostDeleteAsync() handlers
//     replacing AutoGenerateEditButton/AutoGenerateDeleteButton on GridView

using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Tour_Management.Pages
{
    public class TourCrudModel : PageModel
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger<TourCrudModel> _logger;

        public TourCrudModel(IConfiguration configuration, ILogger<TourCrudModel> logger)
        {
            _configuration = configuration;
            _logger = logger;
        }

        public IEnumerable<TourViewModel> Tours { get; set; } = new List<TourViewModel>();
        public string StatusMessage { get; set; } = string.Empty;

        // Retrieve the RDS Proxy connection string from environment variable,
        // falling back to the appsettings.json connectionString for local development.
        private string GetConnectionString()
        {
            return Environment.GetEnvironmentVariable("DB_CONNECTION_STRING")
                ?? _configuration.GetConnectionString("dbconnection")
                ?? string.Empty;
        }

        // Replaces Web Forms Page_Load / refreshdata() pattern (lines 15 and 18)
        public async Task OnGetAsync()
        {
            // Use Dapper with RDS Proxy-backed SqlConnection for cloud-native connection pooling.
            using (IDbConnection conn = new SqlConnection(GetConnectionString()))
            {
                string selectQuery = "SELECT TOUR_ID, TOUR_NAME, PLACE, DAYS, PRICE, LOCATIONS, TOUR_INFO, pic FROM Tour";
                Tours = await conn.QueryAsync<TourViewModel>(selectQuery);
            }
        }

        // Replaces AutoGenerateEditButton on asp:GridView with UpdateCommand on asp:SqlDataSource
        public async Task<IActionResult> OnPostEditAsync(
            int tourId, string tourName, string place, int days,
            string price, string locations, string tourInfo)
        {
            try
            {
                using (IDbConnection conn = new SqlConnection(GetConnectionString()))
                {
                    string updateQuery = "UPDATE [Tour] SET [TOUR_NAME]=@TourName, [PLACE]=@Place, " +
                                        "[DAYS]=@Days, [PRICE]=@Price, [LOCATIONS]=@Locations, " +
                                        "[TOUR_INFO]=@TourInfo WHERE [TOUR_ID]=@TourId";
                    await conn.ExecuteAsync(updateQuery, new
                    {
                        TourId    = tourId,
                        TourName  = tourName,
                        Place     = place,
                        Days      = days,
                        Price     = price,
                        Locations = locations,
                        TourInfo  = tourInfo
                    });
                }
                _logger.LogInformation("Tour {TourId} updated successfully.", tourId);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating tour {TourId}.", tourId);
                StatusMessage = "Update failed. Please try again.";
            }

            return RedirectToPage();
        }

        // Replaces AutoGenerateDeleteButton on asp:GridView with DeleteCommand on asp:SqlDataSource
        public async Task<IActionResult> OnPostDeleteAsync(int tourId)
        {
            try
            {
                using (IDbConnection conn = new SqlConnection(GetConnectionString()))
                {
                    string deleteQuery = "DELETE FROM [Tour] WHERE [TOUR_ID]=@TourId";
                    await conn.ExecuteAsync(deleteQuery, new { TourId = tourId });
                }
                _logger.LogInformation("Tour {TourId} deleted successfully.", tourId);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting tour {TourId}.", tourId);
                StatusMessage = "Delete failed. Please try again.";
            }

            return RedirectToPage();
        }
    }

    public class TourViewModel
    {
        public int TourId { get; set; }
        public string TourName { get; set; } = string.Empty;
        public string Place { get; set; } = string.Empty;
        public int Days { get; set; }
        public string Price { get; set; } = string.Empty;
        public string Locations { get; set; } = string.Empty;
        public string TourInfo { get; set; } = string.Empty;
        public string Pic { get; set; } = string.Empty;
    }
}
